### ISSUE TITLE
Error occurred while enabling AdvancedSpyInventory v2.4.1 (Is it up to date?) java.lang.ExceptionInInitializerError: null

### ISSUE THREAD

**Issue by BomboNators** [DailyCraft/AdvancedSpyInventory#26]
[21:01:21 ERROR]: Error occurred while enabling AdvancedSpyInventory v2.4.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at mc.dailycraft.advancedspyinventory.Main.onEnable(Main.java:53) ~[AdvancedSpyInventory.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:656) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:567) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "mc.dailycraft.advancedspyinventory.utils.Translation.format(String, Object[])" because the return value of "mc.dailycraft.advancedspyinventory.utils.Translation.of()" is null
	at mc.dailycraft.advancedspyinventory.utils.Permissions.<init>(Permissions.java:77) ~[AdvancedSpyInventory.jar:?]
	at mc.dailycraft.advancedspyinventory.utils.Permissions.<clinit>(Permissions.java:15) ~[AdvancedSpyInventory.jar:?]
	... 13 more

**Comment by BomboNators** [comment]
Who to fix?
