### ISSUE TITLE
No Tab completion

### ISSUE THREAD

**Issue by kentonc04** [DailyCraft/AdvancedSpyInventory#27]
whenever typing any AdvancedSpyInventory command it spams the console and says in chat "an internal error occurred while attempting to tab-complete this command". 
Running on Pufferfish 1.20.4, same error on Paper
running mod ver 2.4.2

console log: 

```
 _[15:03:28 ERROR]: Exception when {my mc name} attempted to tab complete inv
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/inv ' in plugin AdvancedSpyInventory v2.4.2
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.Command.tabComplete(Command.java:93) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:240) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.tabCompleteCommand(CraftServer.java:2538) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.tabComplete(CraftServer.java:2510) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.2.9.jar:git-Pufferfish-46]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:551) ~[pufferfish-1.20.4.jar:?]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:531) ~[pufferfish-1.20.4.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.sendServerSuggestions(ServerGamePacketListenerImpl.java:842) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions0$2(ServerGamePacketListenerImpl.java:808) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1462) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1439) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1362) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1340) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-46]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "name" is null
        at mc.dailycraft.advancedspyinventory.command.PlayerTabExecutor.lambda$onTabComplete$1(PlayerTabExecutor.java:22) ~[AdvancedSpyInventory-2.4.2.jar:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at mc.dailycraft.advancedspyinventory.command.PlayerTabExecutor.onTabComplete(PlayerTabExecutor.java:23) ~[AdvancedSpyInventory-2.4.2.jar:?]
        at mc.dailycraft.advancedspyinventory.command.InventoryCommand.onTabComplete(InventoryCommand.java:93) ~[AdvancedSpyInventory-2.4.2.jar:?]
        at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:141) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 23 more_
```

**Comment by DailyCraft** [comment]
Solved by https://github.com/DailyCraft/AdvancedSpyInventory/commit/0337508e9b17ad6970fc2856aa35c7aec6346c56
