### ISSUE TITLE
no working 1.20.1

### ISSUE THREAD

**Issue by digroDont** [DailyCraft/AdvancedSpyInventory#29]
i'm write command /invsee and  happens error:

[18:42:51 ERROR]: null

org.bukkit.command.CommandException: Unhandled exception executing command 'inv' in plugin AdvancedSpyInventory v2.4.3

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.1.jar:git-Paper-196]

at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-196]

at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]

at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]

at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2354) ~[?:?]

at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2314) ~[?:?]

at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]

at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]

at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]

at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]

at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]

at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]

at java.lang.Thread.run(Thread.java:1570) ~[?:?]

Caused by: java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.PotionMeta.setBasePotionType(org.bukkit.potion.PotionType)'

at mc.dailycraft.advancedspyinventory.utils.ItemStackBuilder.<init>(ItemStackBuilder.java:105) ~[AdvancedSpyInventory-2.4.3.jar:?]

at mc.dailycraft.advancedspyinventory.inventory.PlayerInventory.getItem(PlayerInventory.java:60) ~[AdvancedSpyInventory-2.4.3.jar:?]

at mc.dailycraft.advancedspyinventory.nms.v1_20_R1.NMSContainer.a(NMSContainer.java:48) ~[AdvancedSpyInventory-2.4.3.jar:?]

at net.minecraft.world.inventory.Slot.getItem(Slot.java:51) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:238) ~[?:?]

at net.minecraft.world.inventory.AbstractContainerMenu.addSlotListener(AbstractContainerMenu.java:176) ~[?:?]

at net.minecraft.server.level.ServerPlayer.initMenu(ServerPlayer.java:677) ~[?:?]

at org.bukkit.craftbukkit.v1_20_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:463) ~[paper-1.20.1.jar:git-Paper-196]

at mc.dailycraft.advancedspyinventory.nms.NMSHandler.openInventory(NMSHandler.java:39) ~[AdvancedSpyInventory-2.4.3.jar:?]

at mc.dailycraft.advancedspyinventory.utils.CustomInventoryView.open(CustomInventoryView.java:50) ~[AdvancedSpyInventory-2.4.3.jar:?]

at mc.dailycraft.advancedspyinventory.command.InventoryCommand.onCommand(InventoryCommand.java:60) ~[AdvancedSpyInventory-2.4.3.jar:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]

... 23 more

[18:42:51 ERROR]: Entity threw exception at world:898.6528806910372,77.1260665264769,163.27729307122303

java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.PotionMeta.setBasePotionType(org.bukkit.potion.PotionType)'

at mc.dailycraft.advancedspyinventory.utils.ItemStackBuilder.<init>(ItemStackBuilder.java:105) ~[AdvancedSpyInventory-2.4.3.jar:?]

at mc.dailycraft.advancedspyinventory.inventory.PlayerInventory.getItem(PlayerInventory.java:60) ~[AdvancedSpyInventory-2.4.3.jar:?]

at mc.dailycraft.advancedspyinventory.nms.v1_20_R1.NMSContainer.a(NMSContainer.java:48) ~[AdvancedSpyInventory-2.4.3.jar:?]

at net.minecraft.world.inventory.Slot.getItem(Slot.java:51) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:238) ~[?:?]

at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:723) ~[?:?]

at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1352) ~[?:?]

at net.minecraft.world.level.Level.guardEntityTick(Level.java:1004) ~[?:?]

at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:872) ~[?:?]

at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]

at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1556) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]

at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]

at java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by DailyCraft** [comment]
This issue has been fixed in version 2.4.4
