### ISSUE TITLE
Can't open villager inventory

### ISSUE THREAD

**Issue by ravel10** [DailyCraft/AdvancedSpyInventory#30]
When i try to open a villager's inventory i have this error:
```[19:26:40 ERROR]: Entity threw exception at world:178.80567622270513,72.0,-11.86573229613308
java.lang.IllegalArgumentException: object is not an instance of declaring class
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at AdvancedSpyInventory-2.4.5.jar/mc.dailycraft.advancedspyinventory.utils.ClassChange.enumName(ClassChange.java:23) ~[AdvancedSpyInventory-2.4.5.jar:?]
        at AdvancedSpyInventory-2.4.5.jar/mc.dailycraft.advancedspyinventory.inventory.entity.EntityInventory.lambda$static$25(EntityInventory.java:303) ~[AdvancedSpyInventory-2.4.5.jar:?]
        at AdvancedSpyInventory-2.4.5.jar/mc.dailycraft.advancedspyinventory.utils.DataItem.get(DataItem.java:24) ~[AdvancedSpyInventory-2.4.5.jar:?]
        at AdvancedSpyInventory-2.4.5.jar/mc.dailycraft.advancedspyinventory.inventory.entity.EntityInventory.getItem(EntityInventory.java:82) ~[AdvancedSpyInventory-2.4.5.jar:?]
        at AdvancedSpyInventory-2.4.5.jar/mc.dailycraft.advancedspyinventory.nms.v1_21_R1.NMSContainer.getItem(NMSContainer.java:48) ~[AdvancedSpyInventory-2.4.5.jar:?]
        at net.minecraft.world.inventory.Slot.getItem(Slot.java:50) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:238) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:775) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.jar:1.21-124-df3b654]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-124-df3b654]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Edit:
I forgot to mention that I'm on Paper 1.21

**Comment by knightmar** [comment]
Same error on my side with paper 1.21
